


import { Post, PostType, Specialty, User, Product, Job, ReactionType, UserStatus, SpecialtyStat, PostVisibility, Language, MediaType, ProfileVisibility, MessagePermission, Conversation, Message, BackgroundTheme, MuseumCase } from './types';

export const TRANSLATIONS = {
  en: {
    appTitle: 'WeDENTpro',
    tagline: 'Digital Dental Solutions',
    mainMenu: 'Main Menu',
    specialties: 'Specialties',
    generalWall: 'General Wall',
    marketplace: 'Marketplace',
    jobs: 'Jobs & CVs',
    viewProfile: 'View Profile',
    members: 'Members',
    available: 'Available',
    active: 'Active',
    search: 'Search...',
    createPostPlaceholder: 'Share a case, question, or article...',
    post: 'Post',
    addPoll: 'Add Poll',
    pollActive: 'Poll Active',
    photoVideo: 'Photo/Video',
    urgent: 'URGENT',
    consultation: 'CONSULTATION',
    aiConsult: 'Get AI Second Opinion',
    analyzing: 'Analyzing...',
    noPosts: 'No posts yet. Be the first!',
    allSpecialists: 'All Specialists',
    availableSpec: 'Available',
    ad: 'AD',
    trending: 'Trending Article',
    myProfile: 'My Profile',
    logout: 'Logout',
    visibility: 'Visibility',
    vis_personal: 'Post on my wall only',
    vis_specialty: 'Post on specialty wall',
    vis_general: 'Post on general wall',
    vis_all: 'Post on all',
    saveOptions: 'Save these options',
    thisTimeOnly: 'This time only',
    createPoll: 'Create Consultation Poll',
    option: 'Option',
    addOption: 'Add Another Option',
    profileSettings: 'Profile Settings',
    whoCanView: 'Who can view my profile?',
    whoCanMessage: 'Who can message me?',
    everyone: 'Everyone',
    onlyMembers: 'Members Only',
    onlyMe: 'Only Me',
    sameSpecialty: 'Same Specialty',
    noOne: 'No One',
    privateProfile: 'This profile is private.',
    saveSettings: 'Save Settings',
    close: 'Close',
    verified: 'Verified',
    schedulePost: 'Schedule Post',
    postNow: 'Post now',
    scheduleDate: 'Schedule post for:',
    postAfter: 'Post after:',
    days: 'days',
    schedule: 'Schedule',
    followers: 'Followers',
    follow: 'Follow',
    unfollow: 'Unfollow',
    message: 'Message',
    addFriend: 'Add Friend',
    pending: 'Pending',
    // Museum
    weDentMuseum: 'WeDent Museum',
    museumDesc: 'A collection of excellence in dentistry',
    patientReview: 'Patient Review',
    treatmentBy: 'Treatment by',
    viewOriginalPost: 'View Original Post',
    addToFav: 'Add to Favorites',
    removeFromFav: 'Remove from Favorites',
    favorites: 'Favorites',
    // 3D Models
    add3DModel: '3D Model',
    selectModel: 'Select 3D Model',
    modelTeeth: 'Teeth',
    modelBones: 'Bones',
    modelMuscles: 'Muscles',
    modelNerves: 'Nerves',
    modelArteries: 'Arteries',
    interactHint: 'Drag to rotate • Scroll to zoom • Click points',
    partSelected: 'Selected Part:',
    // Ad Management
    createAd: 'Create Ad',
    adManagement: 'Ad Management',
    adStartDate: 'Start Date',
    adDuration: 'Duration',
    adLink: 'Target URL',
    adBtnText: 'Button Text',
    sponsored: 'Sponsored',
    adActive: 'Active',
    adScheduled: 'Scheduled',
    adExpired: 'Expired',
    duration7: '7 Days',
    duration30: '30 Days',
    durationCustom: 'Custom',
    createAdBtn: 'Launch Ad',
    // Interactions
    savePost: 'Save Post',
    unsavePost: 'Unsave Post',
    reportPost: 'Report Post',
    sharePost: 'Share Post',
    comments: 'Comments',
    writeComment: 'Write a comment...',
    send: 'Send',
    reported: 'Post reported successfully',
    saved: 'Post saved to archive',
    removed: 'Post removed from archive',
    commentsDisabled: 'Comments are turned off for this post.',
    reply: 'Reply',
    replies: 'Replies',
    viewReplies: 'View replies',
    hideReplies: 'Hide replies',
    writeReply: 'Write a reply...',
    like: 'Like',
    // Messaging
    messages: 'Messages',
    typeMessage: 'Type a message...',
    noMessages: 'No messages yet',
    startConversation: 'Start a conversation',
    // Backgrounds
    appearance: 'Appearance',
    background: 'App Background',
    defaultBg: 'Default',
    customBg: 'Custom Image',
    upload: 'Upload',
    // Login & Welcome
    fullName: 'Full Name',
    emailLabel: 'Email Address',
    roleLabel: 'I am a...',
    selectRole: 'Select your role',
    specialtyLabel: 'Specialty',
    joinNetwork: 'Join Network',
    welcome: 'Welcome',
    welcomeMsg: "Welcome to our platform! We're glad you're here.",
    // Verification
    verificationTitle: 'Professional Verification',
    policyNotice: 'Policy Notice:',
    policyText: 'WeDENTpro adheres to a strict and clear policy regarding specialization to ensure benefit and patient safety. Please verify your credentials to access specialized clinical discussions.',
    uploadPrompt: 'Please select an option to proceed:',
    tapToUpload: 'Tap to Upload',
    cameraOrGallery: 'Camera or Gallery',
    selected: 'Selected',
    verifyContinue: 'Verify & Continue',
    uploadLater: "I'll upload it later",
    uploadRequiredDocs: "Upload Required Documents",
    uploadLaterOption: "I'll Upload Documents Later",
    enter: "Enter",
    verifyLaterWarning: 'Verifying later may limit access to certain urgent consultation features.',
    skipConfirm: 'Are you sure? Verifying your specialty allows you full access to sensitive clinical discussions. You can verify later from your profile.',
  },
  ar: {
    appTitle: 'ويدينت برو',
    tagline: 'حلول طب الأسنان الرقمية',
    mainMenu: 'القائمة الرئيسية',
    specialties: 'التخصصات',
    generalWall: 'الحائط العام',
    marketplace: 'المتجر',
    jobs: 'وظائف وسير ذاتية',
    viewProfile: 'عرض الملف الشخصي',
    members: 'أعضاء',
    available: 'متاح',
    active: 'نشط',
    search: 'بحث...',
    createPostPlaceholder: 'شارك حالة، سؤال، أو مقال...',
    post: 'نشر',
    addPoll: 'إضافة تصويت',
    pollActive: 'التصويت مفعل',
    photoVideo: 'صورة/فيديو',
    urgent: 'عاجل',
    consultation: 'استشارة',
    aiConsult: 'رأي الذكاء الاصطناعي',
    analyzing: 'جاري التحليل...',
    noPosts: 'لا توجد منشورات بعد. كن الأول!',
    allSpecialists: 'كل الأخصائيين',
    availableSpec: 'متاح',
    ad: 'إعلان',
    trending: 'مقال رائج',
    myProfile: 'ملفي الشخصي',
    logout: 'تسجيل الخروج',
    visibility: 'الظهور',
    vis_personal: 'نشر على حائطي فقط',
    vis_specialty: 'نشر على حائط التخصص',
    vis_general: 'نشر على الحائط العام',
    vis_all: 'نشر على الكل',
    saveOptions: 'حفظ هذه الخيارات',
    thisTimeOnly: 'هذه المرة فقط',
    createPoll: 'إنشاء تصويت استشاري',
    option: 'خيار',
    addOption: 'إضافة خيار آخر',
    profileSettings: 'إعدادات الملف الشخصي',
    whoCanView: 'من يمكنه رؤية ملفي؟',
    whoCanMessage: 'من يمكنه مراسلتي؟',
    everyone: 'الجميع',
    onlyMembers: 'الأعضاء فقط',
    onlyMe: 'أنا فقط',
    sameSpecialty: 'نفس التخصص',
    noOne: 'لا أحد',
    privateProfile: 'هذا الملف الشخصي خاص.',
    saveSettings: 'حفظ الإعدادات',
    close: 'إغلاق',
    verified: 'موثق',
    schedulePost: 'جدولة المنشور',
    postNow: 'نشر الآن',
    scheduleDate: 'جدولة لتاريخ:',
    postAfter: 'نشر بعد:',
    days: 'أيام',
    schedule: 'جدولة',
    followers: 'متابعون',
    follow: 'متابعة',
    unfollow: 'إلغاء المتابعة',
    message: 'رسالة',
    addFriend: 'إضافة صديق',
    pending: 'قيد الانتظار',
    // Museum
    weDentMuseum: 'متحف ويدينت',
    museumDesc: 'مجموعة من التميز في طب الأسنان',
    patientReview: 'رأي المريض',
    treatmentBy: 'العلاج بواسطة',
    viewOriginalPost: 'عرض المنشور الأصلي',
    addToFav: 'إضافة للمفضلة',
    removeFromFav: 'إزالة من المفضلة',
    favorites: 'المفضلة',
    // 3D Models
    add3DModel: 'نموذج 3D',
    selectModel: 'اختر نموذج ثلاثي الأبعاد',
    modelTeeth: 'أسنان',
    modelBones: 'عظام',
    modelMuscles: 'عضلات',
    modelNerves: 'أعصاب',
    modelArteries: 'شرايين',
    interactHint: 'اسحب للتدوير • مرر للتكبير • اضغط للتحديد',
    partSelected: 'الجزء المحدد:',
    // Ad Management
    createAd: 'إنشاء إعلان',
    adManagement: 'إدارة الإعلانات',
    adStartDate: 'تاريخ البدء',
    adDuration: 'المدة',
    adLink: 'رابط الهدف',
    adBtnText: 'نص الزر',
    sponsored: 'مُموَّل',
    adActive: 'نشط',
    adScheduled: 'مجدول',
    adExpired: 'منتهي',
    duration7: '7 أيام',
    duration30: '30 يوم',
    durationCustom: 'مخصص',
    createAdBtn: 'إطلاق الإعلان',
    // Interactions
    savePost: 'حفظ المنشور',
    unsavePost: 'إلغاء الحفظ',
    reportPost: 'إبلاغ عن المنشور',
    sharePost: 'مشاركة المنشور',
    comments: 'تعليقات',
    writeComment: 'اكتب تعليقاً...',
    send: 'إرسال',
    reported: 'تم الإبلاغ عن المنشور',
    saved: 'تم حفظ المنشور في الأرشيف',
    removed: 'تمت إزالة المنشور من الأرشيف',
    commentsDisabled: 'التعليقات مغلقة لهذا المنشور.',
    reply: 'رد',
    replies: 'ردود',
    viewReplies: 'عرض الردود',
    hideReplies: 'إخفاء الردود',
    writeReply: 'اكتب رداً...',
    like: 'إعجاب',
    // Messaging
    messages: 'الرسائل',
    typeMessage: 'اكتب رسالة...',
    noMessages: 'لا توجد رسائل بعد',
    startConversation: 'ابدأ محادثة',
    // Backgrounds
    appearance: 'المظهر',
    background: 'خلفية التطبيق',
    defaultBg: 'الافتراضي',
    customBg: 'صورة مخصصة',
    upload: 'رفع',
    // Login & Welcome
    fullName: 'الاسم الكامل',
    emailLabel: 'البريد الإلكتروني',
    roleLabel: 'صفتي المهنية...',
    selectRole: 'اختر دورك',
    specialtyLabel: 'التخصص',
    joinNetwork: 'انضم للشبكة',
    welcome: 'مرحباً',
    welcomeMsg: "مرحباً بك في منصتنا! نحن سعداء بوجودك هنا.",
    // Verification
    verificationTitle: 'التحقق المهني',
    policyNotice: 'تنويه سياسة الاستخدام:',
    policyText: 'تلتزم WeDENTpro بسياسة صارمة بخصوص التخصص لضمان سلامة المرضى. يرجى التحقق من أوراق اعتمادك للوصول للمناقشات السريرية.',
    uploadPrompt: 'يرجى تحديد خيار للمتابعة:',
    tapToUpload: 'اضغط للرفع',
    cameraOrGallery: 'كاميرا أو المعرض',
    selected: 'تم اختيار',
    verifyContinue: 'تحقق ومتابعة',
    uploadLater: 'سأقوم بالرفع لاحقاً',
    uploadRequiredDocs: "رفع المستندات المطلوبة",
    uploadLaterOption: "سأقوم برفع المستندات لاحقاً",
    enter: "دخول",
    verifyLaterWarning: 'قد يؤدي التحقق لاحقاً إلى تقييد الوصول لميزات الاستشارات العاجلة.',
    skipConfirm: 'هل أنت متأكد؟ التحقق يتيح لك الوصول الكامل للمناقشات. يمكنك التحقق لاحقاً من ملفك.',
  }
};

export const CURRENT_USER: User = {
  id: 'curr-1',
  name: 'Dr. Alex Mercer',
  specialty: Specialty.SURGERY,
  avatar: 'https://picsum.photos/seed/user1/100/100',
  isVerified: true,
  status: UserStatus.AVAILABLE,
  profileVisibility: ProfileVisibility.EVERYONE,
  messagePermission: MessagePermission.EVERYONE,
  followers: 342,
  isFollowing: false,
  isFriend: false,
  isAdmin: true // Set to true for demonstration of Admin features
};

export const SPECIALTIES_LIST = [
  { id: Specialty.GENERAL, label: 'General Wall', labelAr: 'الحائط العام', icon: 'LayoutGrid' },
  { id: Specialty.SURGERY, label: 'Oral Surgery', labelAr: 'جراحة الوجه والفكين', icon: 'Scalpel' },
  { id: Specialty.ENDO, label: 'Endodontics', labelAr: 'علاج الجذور', icon: 'Activity' },
  { id: Specialty.ORTHO, label: 'Orthodontics', labelAr: 'تقويم الأسنان', icon: 'Smile' },
  { id: Specialty.PEDO, label: 'Pediatric', labelAr: 'طب أسنان الأطفال', icon: 'Baby' },
  { id: Specialty.PERIO, label: 'Periodontology', labelAr: 'أمراض اللثة', icon: 'Gem' },
  { id: Specialty.PROSTH, label: 'Prosthodontics', labelAr: 'التعويضات السنية', icon: 'Crown' },
  { id: Specialty.COSMETIC, label: 'Cosmetic', labelAr: 'تجميل الأسنان', icon: 'Sparkles' },
  { id: Specialty.CAFE, label: 'Dental Café', labelAr: 'مقهى الأسنان', icon: 'Coffee' },
];

export const MOCK_DOCTORS: User[] = [
  { id: 'd1', name: 'Dr. Sarah Jenning', specialty: Specialty.ORTHO, avatar: 'https://picsum.photos/seed/d1/100/100', isVerified: true, status: UserStatus.AVAILABLE, profileVisibility: ProfileVisibility.EVERYONE, messagePermission: MessagePermission.EVERYONE, followers: 1240, isFollowing: false, isFriend: true },
  { id: 'd2', name: 'Dr. Mike Ross', specialty: Specialty.SURGERY, avatar: 'https://picsum.photos/seed/d2/100/100', isVerified: true, status: UserStatus.UNAVAILABLE, profileVisibility: ProfileVisibility.MEMBERS, messagePermission: MessagePermission.SAME_SPECIALTY, followers: 580, isFollowing: true, isFriend: false },
  { id: 'd3', name: 'Dr. Emily Blunt', specialty: Specialty.ENDO, avatar: 'https://picsum.photos/seed/d3/100/100', isVerified: false, status: UserStatus.AVAILABLE, profileVisibility: ProfileVisibility.EVERYONE, messagePermission: MessagePermission.EVERYONE, followers: 230, isFollowing: false, isFriend: false },
  { id: 'd4', name: 'Dr. John Doe', specialty: Specialty.PEDO, avatar: 'https://picsum.photos/seed/d4/100/100', isVerified: true, status: UserStatus.AVAILABLE, profileVisibility: ProfileVisibility.ONLY_ME, messagePermission: MessagePermission.NO_ONE, followers: 45, isFollowing: false, isFriend: false },
  { id: 'd5', name: 'Dr. Alan Grant', specialty: Specialty.SURGERY, avatar: 'https://picsum.photos/seed/d5/100/100', isVerified: true, status: UserStatus.AVAILABLE, profileVisibility: ProfileVisibility.EVERYONE, messagePermission: MessagePermission.EVERYONE, followers: 890, isFollowing: true, isFriend: true },
  { id: 'd6', name: 'Dr. Ellie Sattler', specialty: Specialty.PERIO, avatar: 'https://picsum.photos/seed/d6/100/100', isVerified: true, status: UserStatus.UNAVAILABLE, profileVisibility: ProfileVisibility.MEMBERS, messagePermission: MessagePermission.SAME_SPECIALTY, followers: 670, isFollowing: false, isFriend: false },
  { id: 'd7', name: 'Dr. Ian Malcolm', specialty: Specialty.CAFE, avatar: 'https://picsum.photos/seed/d7/100/100', isVerified: false, status: UserStatus.AVAILABLE, profileVisibility: ProfileVisibility.EVERYONE, messagePermission: MessagePermission.EVERYONE, followers: 2100, isFollowing: true, isFriend: false },
  { id: 'd8', name: 'Dr. Gregory House', specialty: Specialty.GENERAL, avatar: 'https://picsum.photos/seed/d8/100/100', isVerified: true, status: UserStatus.AVAILABLE, profileVisibility: ProfileVisibility.EVERYONE, messagePermission: MessagePermission.SAME_SPECIALTY, followers: 5000, isFollowing: false, isFriend: false },
];

export const BACKGROUND_THEMES: BackgroundTheme[] = [
    { id: 'default', name: 'Default', type: 'COLOR', value: 'bg-slate-50' },
    { id: 'clinical', name: 'Clinical Blue', type: 'GRADIENT', value: 'bg-gradient-to-br from-blue-50 to-teal-50' },
    { id: 'dental', name: 'Clean White', type: 'COLOR', value: 'bg-white' },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
    {
        id: 'conv1',
        participants: [MOCK_DOCTORS[0]],
        unreadCount: 2,
        messages: [
            { id: 'm1', senderId: 'd1', content: 'Hi Dr. Mercer, thanks for your presentation!', timestamp: '2h ago', isRead: true },
            { id: 'm2', senderId: 'curr-1', content: 'You are welcome, Sarah!', timestamp: '1h ago', isRead: true },
            { id: 'm3', senderId: 'd1', content: 'Do you have time to discuss the case details?', timestamp: '10m ago', isRead: false },
            { id: 'm4', senderId: 'd1', content: 'I have a similar patient.', timestamp: '5m ago', isRead: false },
        ]
    },
    {
        id: 'conv2',
        participants: [MOCK_DOCTORS[4]],
        unreadCount: 0,
        messages: [
            { id: 'm1', senderId: 'd5', content: 'Are you going to the conference?', timestamp: '1d ago', isRead: true },
            { id: 'm2', senderId: 'curr-1', content: 'Yes, see you there.', timestamp: '1d ago', isRead: true },
        ]
    }
];

export const SPECIALTY_STATS: SpecialtyStat[] = [
  { id: Specialty.GENERAL, membersCount: 15420, availableSpecialists: 142, unavailableSpecialists: 85, activeCount: 1205, engagementLevel: 95 },
  { id: Specialty.SURGERY, membersCount: 3200, availableSpecialists: 45, unavailableSpecialists: 12, activeCount: 320, engagementLevel: 88 },
  { id: Specialty.ENDO, membersCount: 2800, availableSpecialists: 38, unavailableSpecialists: 8, activeCount: 250, engagementLevel: 76 },
  { id: Specialty.ORTHO, membersCount: 3100, availableSpecialists: 52, unavailableSpecialists: 15, activeCount: 290, engagementLevel: 82 },
  { id: Specialty.PEDO, membersCount: 1900, availableSpecialists: 24, unavailableSpecialists: 6, activeCount: 180, engagementLevel: 65 },
  { id: Specialty.PERIO, membersCount: 1500, availableSpecialists: 18, unavailableSpecialists: 9, activeCount: 150, engagementLevel: 55 },
  { id: Specialty.PROSTH, membersCount: 1200, availableSpecialists: 15, unavailableSpecialists: 5, activeCount: 110, engagementLevel: 48 },
  { id: Specialty.COSMETIC, membersCount: 4500, availableSpecialists: 80, unavailableSpecialists: 25, activeCount: 450, engagementLevel: 92 },
  { id: Specialty.CAFE, membersCount: 8000, availableSpecialists: 200, unavailableSpecialists: 150, activeCount: 800, engagementLevel: 98 },
];

export const MOCK_POSTS: Post[] = [
  {
    id: 'p1',
    author: MOCK_DOCTORS[0],
    type: PostType.CASE,
    specialty: Specialty.GENERAL, 
    visibility: PostVisibility.GENERAL,
    title: 'Consultation: Prognosis of Tooth #36 with Furcation Involvement',
    content: 'Patient (45M) presents with Class II furcation involvement on #36 and periodontal pocketing of 6mm. Mobility is Grade I. The tooth is asymptomatic but radiographic analysis shows bone loss. I am debating the best conservative vs surgical approach. Please vote on your recommended treatment plan.',
    reactions: {
        [ReactionType.LIKE]: 12,
        [ReactionType.THINKING]: 15,
        [ReactionType.LEARNED]: 2,
        [ReactionType.LOVE]: 5,
        [ReactionType.SURPRISED]: 0
    },
    comments: [
        { 
            id: 'c1', 
            author: MOCK_DOCTORS[1], 
            content: 'I would recommend extracting and placing an immediate implant if bone allows.', 
            timestamp: '1h ago', 
            reactions: {'LOVE': 2},
            replies: [
                { id: 'r1', author: MOCK_DOCTORS[0], content: 'Bone width is borderline (6mm). Would you still proceed?', timestamp: '50m ago', reactions: {} }
            ]
        }
    ],
    timestamp: '2h ago',
    media: [
        { type: MediaType.IMAGE, url: 'https://picsum.photos/seed/ortho1/600/400' }
    ],
    poll: {
        totalVotes: 42,
        options: [
            { id: 'opt1', text: 'Extraction & Implant', votes: 8 },
            { id: 'opt2', text: 'Gum Treatment (Perio Surgery)', votes: 12 },
            { id: 'opt3', text: 'Root Canal Treatment (Endo)', votes: 18 },
            { id: 'opt4', text: 'Other / Monitoring', votes: 4 },
        ]
    },
    isSaved: false,
    allowComments: true
  },
  {
    id: 'p2',
    author: MOCK_DOCTORS[1],
    type: PostType.URGENT,
    specialty: Specialty.SURGERY,
    visibility: PostVisibility.ALL,
    title: 'URGENT: Ludwigs Angina Complication',
    content: 'Need immediate advice on airway management protocol for a patient showing early signs of Ludwig\'s post-extraction of #38. Swelling is bilateral submandibular.',
    isUrgent: true,
    reactions: {
        [ReactionType.LIKE]: 45,
        [ReactionType.THINKING]: 20,
        [ReactionType.LEARNED]: 89,
        [ReactionType.LOVE]: 10,
        [ReactionType.SURPRISED]: 12
    },
    comments: [],
    timestamp: '15m ago',
    isSaved: true,
    allowComments: true
  },
  {
    id: 'p3',
    author: MOCK_DOCTORS[2],
    type: PostType.ARTICLE,
    specialty: Specialty.ENDO,
    visibility: PostVisibility.SPECIALTY,
    title: 'MB2 Canal Location Techniques using CBCT',
    content: 'A recent study shows that MB2 canals are missed in over 40% of maxillary molar treatments without magnification. Here is my protocol for locating them...',
    reactions: {
        [ReactionType.LIKE]: 120,
        [ReactionType.THINKING]: 10,
        [ReactionType.LEARNED]: 200,
        [ReactionType.LOVE]: 45,
        [ReactionType.SURPRISED]: 5
    },
    comments: [],
    timestamp: '5h ago',
    media: [
        { type: MediaType.IMAGE, url: 'https://picsum.photos/seed/endo1/600/400' }
    ],
    isSaved: false,
    allowComments: true
  },
  {
    id: 'p4',
    author: MOCK_DOCTORS[3],
    type: PostType.FUN,
    specialty: Specialty.CAFE,
    visibility: PostVisibility.ALL,
    title: 'When the patient says they floss daily...',
    content: '...but the gums start bleeding as soon as you look at them. 😂 #DentistLife',
    reactions: {
        [ReactionType.LIKE]: 230,
        [ReactionType.THINKING]: 0,
        [ReactionType.LEARNED]: 0,
        [ReactionType.LOVE]: 150,
        [ReactionType.SURPRISED]: 2
    },
    comments: [],
    timestamp: '1d ago',
    media: [
        { type: MediaType.IMAGE, url: 'https://picsum.photos/seed/meme1/600/400' }
    ],
    isSaved: false,
    allowComments: true
  }
];

export const MOCK_MUSEUM_CASES: MuseumCase[] = [
    {
        id: 'mc1',
        postId: 'p101',
        title: 'Full Arch Rehabilitation with Zirconia Bridges',
        category: Specialty.PROSTH,
        image: 'https://picsum.photos/seed/case1/800/600',
        doctor: MOCK_DOCTORS[4],
        rating: 5,
        patientReview: '"Dr. Grant completely transformed my smile. I can eat apples again! The attention to detail was incredible."',
        isFavorite: false
    },
    {
        id: 'mc2',
        postId: 'p102',
        title: 'Minimally Invasive Veneers - 10 Units',
        category: Specialty.COSMETIC,
        image: 'https://picsum.photos/seed/case2/800/600',
        doctor: MOCK_DOCTORS[0],
        rating: 4.8,
        patientReview: '"I wanted a natural look and Dr. Jenning delivered exactly that. The procedure was painless and quick."',
        isFavorite: true
    },
    {
        id: 'mc3',
        postId: 'p103',
        title: 'Complex Class II Correction with Invisalign',
        category: Specialty.ORTHO,
        image: 'https://picsum.photos/seed/case3/800/600',
        doctor: MOCK_DOCTORS[0],
        rating: 5,
        patientReview: '"My bite feels perfect now. I never thought clear aligners could fix my severe overbite, but they did!"',
        isFavorite: false
    },
    {
        id: 'mc4',
        postId: 'p104',
        title: 'Surgical Management of Impacted Canines',
        category: Specialty.SURGERY,
        image: 'https://picsum.photos/seed/case4/800/600',
        doctor: MOCK_DOCTORS[1],
        rating: 4.9,
        patientReview: '"Recovery was faster than expected. The doctor explained every step clearly which calmed my anxiety."',
        isFavorite: false
    }
];

export const MOCK_PRODUCTS: Product[] = [
  { id: 'pr1', title: 'Planmeca ProMax 3D', price: 15000, condition: 'Used', category: 'Imaging', image: 'https://picsum.photos/seed/xray/300/300', seller: MOCK_DOCTORS[1] },
  { id: 'pr2', title: 'NSK Ti-Max Z95L Handpiece', price: 600, condition: 'Like New', category: 'Instruments', image: 'https://picsum.photos/seed/drill/300/300', seller: MOCK_DOCTORS[0] },
  { id: 'pr3', title: 'Dental Chair Unit - Adec 500', price: 4500, condition: 'Refurbished', category: 'Furniture', image: 'https://picsum.photos/seed/chair/300/300', seller: MOCK_DOCTORS[2] },
];

export const MOCK_JOBS: Job[] = [
  { id: 'j1', title: 'Associate Dentist', clinic: 'Bright Smiles Family Dental', location: 'New York, NY', type: 'Full-time', salaryRange: '$180k - $250k', postedDate: '2d ago', requirements: ['3+ years experience', 'Molar Endo proficiency'] },
  { id: 'j2', title: 'Orthodontist', clinic: 'Elite Ortho Center', location: 'Los Angeles, CA', type: 'Part-time', salaryRange: '$1500/day', postedDate: '5d ago', requirements: ['Board Certified', 'Invisalign Gold Provider'] },
];
